import type { AppProps } from "next/app";
import { Hydrate, QueryClientProvider } from "react-query";
import { queryClient } from "../core/queryClient";
import Head from "next/head";
import "../styles/globals.css";
import { createContext, useMemo, useState } from "react";

export const AuthContext = createContext({
  isRegistered: false,
  setIsRegistered: (agr: boolean) => {},
  id: 0,
  setId: (arg: number) => {},
});
function MyApp({ Component, pageProps }: AppProps) {
  const { queryDehydratedState } = pageProps;
  const [isRegistered, setIsRegistered] = useState(false);
  const [id, setId] = useState(0);
  const contextValue = useMemo(
    () => ({
      isRegistered,
      setIsRegistered,
      id,
      setId,
    }),
    [isRegistered]
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthContext.Provider value={contextValue}>
        <QueryClientProvider client={queryClient}>
          <Hydrate state={queryDehydratedState}>
            <Component {...pageProps} />
          </Hydrate>
        </QueryClientProvider>
      </AuthContext.Provider>
    </>
  );
}

export default MyApp;
